src/apps/exam/urls.py
from django.conf.urls import patterns, url


exam_urlpatterns = patterns(
    'src.apps.exam.views',
    url(r'^test/(?P<test_id>\d+)$', 'test_view', name='test'),
    url(r'^test/(?P<test_id>\d+)/offline$', 'test_view', name='test-offline',
        kwargs={'offline': True}),
    url(r'^$', 'index_view'),
)

src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

from apps.exam.urls import exam_urlpatterns


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/exam')),
    url(r'^exam/', include(exam_urlpatterns, namespace='exam', app_name='exam')),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls'))
]

src/apps/exam/models.py
# -*- coding: utf-8 -*-
import json
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import JSONField # in Django 1.9


class NamedItem(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class AnswerItem(NamedItem):
    class Meta:
        verbose_name = u"Ответ"
        verbose_name_plural = u"Ответы"


class QuestionItem(NamedItem):
    answers = models.ManyToManyField(AnswerItem, through='QuestionAnswers')

    class Meta:
        verbose_name = u"Вопрос"
        verbose_name_plural = u"Вопросы"

    def to_dict(self, with_right_answers=None):
        """Returns a serialized question
        :param with_right_answers:
        :return:
        """
        ra = lambda x: {'is_right': x.answer.is_right} \
            if with_right_answers else {}
        answers = QuestionAnswers.objects.filter(question=self)
        return dict(
            pk=self.pk,
            name=self.name,
            answers=[dict(pk=a.pk, name=unicode(a.answer), **ra(a))
                     for a in answers]
        )


class QuestionAnswers(models.Model):
    question = models.ForeignKey(QuestionItem, on_delete=models.CASCADE)
    answer = models.ForeignKey(AnswerItem, on_delete=models.CASCADE)
    is_right = models.BooleanField(u"Правильный ответ", default=False)


class TestItemManager(models.Manager):
    def all_with_passed_count(self):
        tests_list = self.all()
        passed_list = TestResult.objects.values('test').annotate(
            passed_count=models.Count('test')
        ).order_by().values_list('test_id', 'passed_count')
        for test in tests_list:
            test.passed_count = dict(passed_list).get(test.id, 0)
        return tests_list


class TestItem(NamedItem):
    questions = models.ManyToManyField(QuestionItem, through='TestQuestions')

    objects = TestItemManager()

    class Meta:
        verbose_name = u"Тест"
        verbose_name_plural = u"Тесты"

    def to_dict(self, with_right_answers=None):
        return dict(
            pk=self.pk,
            name=self.name,
            questions=[q.to_dict(with_right_answers)
                       for q in self.questions.select_related()]
        )

    def right_answers_ids_list(self):
        questions_ids_list = self.questions.values_list('id', flat=True)
        answers_ids_list = list(QuestionAnswers.objects.filter(
            is_right=True, question__id__in=questions_ids_list
        ).values_list('id', flat=True))
        answers_ids_list.sort()
        return answers_ids_list


class TestQuestions(models.Model):
    test = models.ForeignKey(TestItem, on_delete=models.CASCADE)
    question = models.ForeignKey(QuestionItem, on_delete=models.CASCADE)
    ordering = models.PositiveSmallIntegerField(
        u"Сортировка", default=0, blank=True)


class TestResult(models.Model):
    user = models.ForeignKey(User)
    test = models.ForeignKey(TestItem, related_name='passed_tests')
    started = models.DateTimeField(
        u'Начало теста', auto_now_add=True, editable=False)
    completed = models.DateTimeField(
        u'Завершение теста', blank=True, null=True)
    is_passed = models.BooleanField(default=False)
    # TODO: use JSONField or ArrayField in Django 1.9
    answers = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = u'Результат тестирования'
        verbose_name_plural = u'Результаты тестирования'
        ordering = ('-started', 'test')

    def __unicode__(self):
        return u'<TestResult: user=\'{0}\', test=\'{1}\', is_passed={2}>' \
               u''.format(self.user, self.test, self.is_passed)

    def complete(self, data):
        self.completed = datetime.now()
        self.set_answers(data)
        self.save()

    def answers_ids_list(self):
        """Workaround JSONField
        :return:
        """
        # TODO: check is the answers field is JSONField
        ids_list = json.loads(self.answers) if self.answers else {}
        ids_list.sort()
        return ids_list

    def set_answers(self, data, save=False):
        """Set answers
        :param data:
        :param save:
        :return:
        """
        if isinstance(data, list):
            self.answers = json.dumps(data)
        elif isinstance(data, basestring) and isinstance(json.loads(data), list):
            self.answers = data
        else:
            return
        if save:
            self.save()

    def check_result(self, save=False):
        """Checks is passed answers are right
        :param save: save result into the DB
        :return:
        """
        right_answers_ids_list = self.test.right_answers_ids_list()
        answers_ids_list = self.answers_ids_list()
        print right_answers_ids_list, answers_ids_list
        result = answers_ids_list == right_answers_ids_list
        if save:
            self.is_passed = result
            self.save()
        return result

src/apps/exam/views.py
from django.views.generic.base import TemplateView
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.template.loader import render_to_string

from .models import TestItem, TestResult


class IndexView(TemplateView):
    template_name = 'tests_index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['tests_list'] = TestItem.objects.all_with_passed_count()
        return context
index_view = login_required(IndexView.as_view(), redirect_field_name='')


class TestView(TemplateView):
    template_name = 'inc/test_form.html'

    def get_context_data(self, **kwargs):
        context = super(TestView, self).get_context_data(**kwargs)
        tid = self.kwargs['test_id']
        test = TestItem.objects.get(pk=tid).to_dict()
        context['test'] = test
        return context

    def _offline(self):
        """Download test template to take it off-line
        :return:
        """
        context = self.get_context_data()
        tid = self.kwargs['test_id']
        test = TestItem.objects.get(pk=tid)
        context['right_answers'] = test.right_answers_ids_list()
        test_template = ContentFile(render_to_string('inc/test_offline.html', context))
        response = HttpResponse(test_template, 'application/html')
        response['Content-Length'] = test_template.size
        response['Content-Disposition'] = 'attachment; filename="test.html"'
        return response

    def get(self, request, *args, **kwargs):
        if self.kwargs.get('offline'):
            return self._offline()
        if request.is_ajax() and not request.GET.get('as_html') == '1':
            return JsonResponse(self.get_context_data()['test'])
        return super(TestView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        tid = self.kwargs['test_id']
        data = request.POST.copy()
        answers = []
        for k in data:
            if k.startswith('q_'):
                answers.extend(data.getlist(k))
        answers = map(int, answers)
        answers.sort()

        test, created = TestResult.objects.get_or_create(
            user=request.user, test_id=tid)
        test.complete(answers)
        result = test.check_result(save=True)
        if request.is_ajax():
            return JsonResponse({'status': result})
        return super(TestView, self).post(request, *args, **kwargs)
test_view = login_required(TestView.as_view(), redirect_field_name='')

src/apps/exam/templates/inc/test_form.html
<form action="{% url 'exam:test' test.pk %}" method="post" id="test-form">
    {% csrf_token %}
    <h3>{{ test.name }}</h3>
    {% if not nodownload %}<a href="{% url 'exam:test-offline' test.pk %}">
        Скачать
    </a>{% endif %}
    <ul class="list-group">
        {% for question in test.questions %}<li class="list-group-item">
            <h4>{{ question.name }}</h4>
            <ul class="list-group">
                {% for answer in question.answers %}<li class="list-group-item">
                    <input type="radio" name="q_{{ question.pk }}"
                           id="q_{{ question.pk }}_{{ answer.pk }}"
                           value="{{ answer.pk }}">
                    <label for="q_{{ question.pk }}_{{ answer.pk }}">
                        {{ answer.name }}
                    </label>
                {% endfor %}
            </ul>
            <span class="badge">{{ test.passed_count }}</span>
        </li>
        {% endfor %}
    </ul>
    <button type="submit" id="test-submit" class="btn btn-success pull-left">
        Отправить
    </button>
    <div class="pull-left" id="test-result"></div>
</form>

src/apps/exam/templates/inc/test_offline.html
{% extends "base_offline.html" %}

{% block main_wrapper %}

{% include "inc/test_form.html" with nodownload=True %}

{% endblock %}


{% block js_load %}
<script type="application/javascript">
    var T = {
        compareArrays: function (a1, a2) {
            if (!a1)
                return false;
            if (a2.length != a1.length)
                return false;
            for (var i = 0, l = a2.length; i < l; i++) {
                if (a2[i] instanceof Array && a1[i] instanceof Array) {
                    if (!a2[i].equals(a1[i]))
                        return false;
                }
                else if(a2[i] != a1[i]) {
                    return false;
                }
            }
            return true;
        },
        serialize: function(form){if(!form||form.nodeName!=="FORM"){return }var i,j,q=[];for(i=form.elements.length-1;i>=0;i=i-1){if(form.elements[i].name===""){continue}switch(form.elements[i].nodeName){case"INPUT":switch(form.elements[i].type){case"text":case"hidden":case"password":case"button":case"reset":case"submit":q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].value));break;case"checkbox":case"radio":if(form.elements[i].checked){q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].value))}break;case"file":break}break;case"TEXTAREA":q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].value));break;case"SELECT":switch(form.elements[i].type){case"select-one":q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].value));break;case"select-multiple":for(j=form.elements[i].options.length-1;j>=0;j=j-1){if(form.elements[i].options[j].selected){q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].options[j].value))}}break}break;case"BUTTON":switch(form.elements[i].type){case"reset":case"submit":case"button":q.push(form.elements[i].name+"="+encodeURIComponent(form.elements[i].value));break}break}}return q.join("&")},
        on: function(elementId, eventName, handler) {
            var element = this.find(elementId);
            element['on' + eventName] = handler;
        },

        find: function(tgt){
            return document.getElementById(tgt);
        },
        data: function(element, attr){
            return element.getAttribute('data-' + attr);
        },
        checkTest: function(answers){
            var rightAnswers = JSON.parse('{{ right_answers|default:"[]" }}');
            return this.compareArrays(answers, rightAnswers);
        }
    };
    (function($){
        var submit = function(){
            var data = $.serialize($.find('test-form')).split('&'),
                answers = [];
            for(var i = 0; i < data.length; i++){
                var d = data[i];
                if(d){
                    answers.push(parseInt(d.split('=')[1]));
                }
            }
            answers.sort();
            var result = $.checkTest(answers);
            alert(result === true ? 'Тест пройден' : 'Тест провален');
            return false;
        };
        $.on('test-submit', 'submit', submit);
        $.on('test-submit', 'click', submit);
    })(T);
</script>
{% endblock %}

src/apps/exam/templates/tests_index.html
{% extends "base.html" %}
{% load assets %}

{% block js_load %}
{% assets "js_exam" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "css_exam" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}

{% block main_wrapper %}

<section id="container">
    <div class="row">
        <div class="col-md-3" id="tests-list">
            <div class="list-group">
                {% for test in tests_list %}<button type="button" class="list-group-item" data-tid="{{ test.id }}">
                    {{ test }}
                    <span class="badge">{{ test.passed_count }}</span>
                </button>
                {% endfor %}
            </div>
        </div>
        <div id="test-info" class="hidden"></div>
    </div>
</section>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r"
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>

    {% block head_extras %}{% endblock %}
</head>
<body>
    <div id="main-wrapper">
        {% block main_wrapper %}{% endblock %}
    </div>

    {% block js_load %}{% endblock %}
</body>
</html>

src/templates/base_offline.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    {% block head_extras %}{% endblock %}
</head>
<style>
    /* Offline test style here */
</style>
<body>
    <div id="main-wrapper">
        {% block main_wrapper %}{% endblock %}
    </div>

    {% block js_load %}{% endblock %}
</body>
</html>